resources:
  repositories:
    - repository: endjin_recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub

jobs:
- template: templates/build.and.release.yml@endjin_recommended_practices