trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:

  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  SolutionToBuild: 'Solutions/Corvus.Extensions.sln'

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Install .NET Core SDK 2.2.401 (Global Tools error workaround)'
  inputs:
    version: 2.2.401

#- task: gittools.gitversion.gitversion-task.GitVersion@5
#  displayName: 'GitVersion'
#  inputs:
#    preferBundledVersion: false
#    additionalArguments: /diag

# NB - In the future the GitVersion commands should be replaced with the GitVersion Azure DevOps task. However that task is currently unstable on Linux build agents.

- task: NuGetCommand@2
  inputs:
    command: custom
    arguments: install GitVersion.CommandLine -Version 4.0.0 -OutputDirectory $(Build.BinariesDirectory)/tools -ExcludeVersion
  displayName: 'Install GitVersion'

- script: mono $(Build.BinariesDirectory)/tools/GitVersion.CommandLine/tools/GitVersion.exe /output buildserver /nofetch
  displayName: 'Determine Version'

- task: DotNetCoreCLI@2
  displayName: 'Restore & Build'
  inputs:
    command: 'build'
    projects: $(SolutionToBuild)
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
    versioningScheme: byBuildNumber

- task: DotNetCoreCLI@2
  displayName: 'Run Executable Specifications'
  inputs:
    command: 'test'
    projects: $(SolutionToBuild)
    arguments: '-c $(BuildConfiguration) --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    nobuild: true

- script: |
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator "-reports:$(Build.SourcesDirectory)/**/**/coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)/CodeCoverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
  displayName: 'Generate Code Coverage Report'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Report'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet Packages'
  inputs:
    command: 'pack'
    projects: $(SolutionToBuild)
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages/$(Build.BuildID)'
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: GitVersion.NuGetVersion

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'