resources:
  repositories:
    - repository: template
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: $(Endjin_Service_Connection_GitHub)

jobs:
- template: templates/build.and.release.yml@template